#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; BUILDER_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

CONFIG_FILE="$TMP_WORK_DIR/.dokku-workspaces"
[[ ! -f "$CONFIG_FILE" ]] && exit

dokku_log_info2 "Workspaces detected (dokku workspaces plugin v 1.0)"

while IFS="=" read -u 10 -a line || [[ -n $line ]]; do
  [[ "${line[0]}" == "#"* || "${line[1]}" == "" ]] && continue
  [[ $APP != *"${line[0]}"* ]] && continue

  workspace="${line[1]}"
  dokku_log_info2 "Generating Procfile for workspace: $workspace"

  echo "web: npm run start -w $workspace" > "$TMP_WORK_DIR/Procfile"
  exit
done 10<"$CONFIG_FILE"

dokku_log_info2 "The application $APP is not defined in .dokku-workspaces!"
exit 1
